version: "2"

services:
  app:
    build:
      context: ../
      dockerfile: ./systems/Dockerfile
    command: >
      bash -c "
        cabal update &&
        cabal install --only-dependencies &&
        cabal run exe:non-stack-yesod
      "
    environment:
      PORT: 3000
      APP_DATABASE: host=postgres port=5432 user=postgres dbname=postgres password=
    ports:
      - 3000:3000
    volumes:
      - ../main.hs:/app/main.hs
      - ../src:/app/src
      - ../cabal.config:/app/cabal.config
      - ../non-stack-yesod.cabal:/app/non-stack-yesod.cabal
      - app_data:/app/dist
      - app_data:/root/.cabal
      - app_data:/root/.ghc

  test:
    build:
      context: ../
      dockerfile: ./systems/Dockerfile
    command: >
      bash -c "
        cabal update &&
        cabal install --only-dependencies --enable-tests &&
        cabal configure --enable-tests &&
        cabal test --show-details=always
      "
    environment:
      APP_DATABASE: host=postgres port=5432 user=postgres dbname=postgres_test password=
    volumes:
      - ../main.hs:/app/main.hs
      - ../src:/app/src
      - ../test:/app/test
      - ../cabal.config:/app/cabal.config
      - ../non-stack-yesod.cabal:/app/non-stack-yesod.cabal
      - app_data:/app/dist
      - app_data:/root/.cabal
      - app_data:/root/.ghc

  postgres:
    image: postgres:9.5.3
    environment:
      POSTGRES_DB: postgres_test
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: hiogawa/flyway:4.0.1
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/postgres
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD:
    volumes:
      - ./sql:/flyway/sql

  flyway_test:
    image: hiogawa/flyway:4.0.1
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/postgres_test
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD:
    volumes:
      - ./sql:/flyway/sql

volumes:
  app_data:
  postgres_data:
